### PR TITLE
adding title dinamic

### PR DESCRIPTION
**Pull request by gabimartini**
trello issue: https://trello.com/c/e6KgkrwE

Screenshot 2022-04-25 at 16 59 15

### CODE REVIEW

**Review by em-cd — COMMENTED** [review]
Looks good - do we need to do the same thing for the other pages? for example the 'Health' and 'Family' pages etc?

**Comment by gabimartini** [comment]
> Looks good - do we need to do the same thing for the other pages? for example the 'Health' and 'Family' pages etc?

I Think it will be good! I will add for the others too 😄

**Comment by gabimartini** [comment]
> Looks good - do we need to do the same thing for the other pages? for example the 'Health' and 'Family' pages etc?

@em-cd  In the image we have the Buckinghamshire adoption service this is also hard code. We can either remove it, or set an input for name the institution or the name of the app. If we will add one of these we can create a new ticket for that. What do you think?

**Comment by em-cd** [comment]
> > Looks good - do we need to do the same thing for the other pages? for example the 'Health' and 'Family' pages etc?
> 
> @em-cd In the image we have the Buckinghamshire adoption service this is also hard code. We can either remove it, or set an input for name the institution or the name of the app. If we will add one of these we can create a new ticket for that. What do you think?

Maybe check with Alex to see if we need to make it configurable too or if we can remove it, and if we need to keep it then yes, definitely make another ticket for it 😄 Thank you!

**Review by em-cd — APPROVED** [review]

**Pull request merged**
